require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UbicacionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ubicacion. As you add validations to Ubicacion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UbicacionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ubicacions as @ubicacions" do
      ubicacion = Ubicacion.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ubicacions)).to eq([ubicacion])
    end
  end

  describe "GET show" do
    it "assigns the requested ubicacion as @ubicacion" do
      ubicacion = Ubicacion.create! valid_attributes
      get :show, {:id => ubicacion.to_param}, valid_session
      expect(assigns(:ubicacion)).to eq(ubicacion)
    end
  end

  describe "GET new" do
    it "assigns a new ubicacion as @ubicacion" do
      get :new, {}, valid_session
      expect(assigns(:ubicacion)).to be_a_new(Ubicacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested ubicacion as @ubicacion" do
      ubicacion = Ubicacion.create! valid_attributes
      get :edit, {:id => ubicacion.to_param}, valid_session
      expect(assigns(:ubicacion)).to eq(ubicacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ubicacion" do
        expect {
          post :create, {:ubicacion => valid_attributes}, valid_session
        }.to change(Ubicacion, :count).by(1)
      end

      it "assigns a newly created ubicacion as @ubicacion" do
        post :create, {:ubicacion => valid_attributes}, valid_session
        expect(assigns(:ubicacion)).to be_a(Ubicacion)
        expect(assigns(:ubicacion)).to be_persisted
      end

      it "redirects to the created ubicacion" do
        post :create, {:ubicacion => valid_attributes}, valid_session
        expect(response).to redirect_to(Ubicacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ubicacion as @ubicacion" do
        post :create, {:ubicacion => invalid_attributes}, valid_session
        expect(assigns(:ubicacion)).to be_a_new(Ubicacion)
      end

      it "re-renders the 'new' template" do
        post :create, {:ubicacion => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ubicacion" do
        ubicacion = Ubicacion.create! valid_attributes
        put :update, {:id => ubicacion.to_param, :ubicacion => new_attributes}, valid_session
        ubicacion.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ubicacion as @ubicacion" do
        ubicacion = Ubicacion.create! valid_attributes
        put :update, {:id => ubicacion.to_param, :ubicacion => valid_attributes}, valid_session
        expect(assigns(:ubicacion)).to eq(ubicacion)
      end

      it "redirects to the ubicacion" do
        ubicacion = Ubicacion.create! valid_attributes
        put :update, {:id => ubicacion.to_param, :ubicacion => valid_attributes}, valid_session
        expect(response).to redirect_to(ubicacion)
      end
    end

    describe "with invalid params" do
      it "assigns the ubicacion as @ubicacion" do
        ubicacion = Ubicacion.create! valid_attributes
        put :update, {:id => ubicacion.to_param, :ubicacion => invalid_attributes}, valid_session
        expect(assigns(:ubicacion)).to eq(ubicacion)
      end

      it "re-renders the 'edit' template" do
        ubicacion = Ubicacion.create! valid_attributes
        put :update, {:id => ubicacion.to_param, :ubicacion => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ubicacion" do
      ubicacion = Ubicacion.create! valid_attributes
      expect {
        delete :destroy, {:id => ubicacion.to_param}, valid_session
      }.to change(Ubicacion, :count).by(-1)
    end

    it "redirects to the ubicacions list" do
      ubicacion = Ubicacion.create! valid_attributes
      delete :destroy, {:id => ubicacion.to_param}, valid_session
      expect(response).to redirect_to(ubicacions_url)
    end
  end

end
